// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Company.Models
{
    public partial class GetAllCustomerProjectsDataResult
    {
        public int CustomerId { get; set; }
        [StringLength(100)]
        public string CustomerName { get; set; }
        [Column("Salary", TypeName = "decimal(18,2)")]
        public decimal Salary { get; set; }
        [StringLength(50)]
        public string Password { get; set; }
        public int DeptId { get; set; }
        [StringLength(50)]
        public string DepartmentName { get; set; }
        public int? ProjectId { get; set; }
        [StringLength(100)]
        public string ProjectName { get; set; }
        [StringLength(2147483647)]
        public string ProjectDescription { get; set; }
    }
}
